import { Knex } from "knex";
import { v4 as uuidv4 } from "uuid";
import { DB_TABLES } from "../shared/enums/db-tables.enum";

const OWNER_1 = "11111111-1111-1111-1111-111111111111"; // Emeka Okafor
const OWNER_2 = "22222222-2222-2222-2222-222222222222"; // Amara Nwosu
const OWNER_3 = "33333333-3333-3333-3333-333333333333"; // Tunde Adeyemi

// Unsplash photo IDs for realistic property images
const IMG = {
  apt1:  "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&auto=format&fit=crop",
  apt2:  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop",
  apt3:  "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&auto=format&fit=crop",
  house1:"https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&auto=format&fit=crop",
  house2:"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&auto=format&fit=crop",
  house3:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop",
  studio:"https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop",
  duplex:"https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop",
  office:"https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop",
  room1: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop",
  room2: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format&fit=crop",
  room3: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&auto=format&fit=crop",
  room4: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&auto=format&fit=crop",
  ext1:  "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&auto=format&fit=crop",
  ext2:  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&auto=format&fit=crop",
};

function slug(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export async function seed(knex: Knex): Promise<void> {
  await knex(DB_TABLES.PROPERTIES).del();

  const now = new Date();

  const properties = [
    // ── Lagos ────────────────────────────────────────────────────────────────
    {
      id: uuidv4(),
      owner_id: OWNER_1,
      title: "Luxury 3-Bedroom Apartment, Lekki Phase 1",
      description:
        "Stunning fully-furnished 3-bedroom apartment in the heart of Lekki Phase 1. Features top-of-the-line finishes, a spacious living room, modern kitchen, and a private balcony with estate views. 24/7 security and dedicated parking.",
      price: 950000,
      location: "Lekki Phase 1, Lagos",
      type: "Apartment",
      rooms: 3,
      amenities: JSON.stringify(["WiFi", "Generator", "Air Conditioning", "Security", "Parking", "Swimming Pool"]),
      verified: true,
      is_available: true,
      views: 214,
      images: [IMG.apt1, IMG.room1, IMG.ext1],
      videos: [],
      slug: slug("Luxury 3-Bedroom Apartment Lekki Phase 1"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_2,
      title: "Cozy Self-Contain in Yaba",
      description:
        "Clean and affordable self-contained apartment in Yaba, Lagos. Perfect for a working professional or student. Walking distance to Yaba College of Technology and major bus stops. Water and electricity reliable.",
      price: 180000,
      location: "Yaba, Lagos",
      type: "Self-contain",
      rooms: 1,
      amenities: JSON.stringify(["Water", "Security", "Tiled Floors"]),
      verified: false,
      is_available: true,
      views: 87,
      images: [IMG.studio, IMG.room2],
      videos: [],
      slug: slug("Cozy Self-Contain in Yaba"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_3,
      title: "Modern 2-Bedroom Flat, Ikeja GRA",
      description:
        "Tastefully furnished 2-bedroom flat in the prestigious Ikeja GRA. Newly renovated with porcelain tiles, modern bathrooms, and a fitted kitchen. Close to MMA2 airport and major business hubs.",
      price: 600000,
      location: "Ikeja GRA, Lagos",
      type: "Apartment",
      rooms: 2,
      amenities: JSON.stringify(["WiFi", "Generator", "Air Conditioning", "Security", "Parking"]),
      verified: true,
      is_available: true,
      views: 155,
      images: [IMG.apt2, IMG.room3, IMG.ext2],
      videos: [],
      slug: slug("Modern 2-Bedroom Flat Ikeja GRA"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_1,
      title: "Studio Apartment, Victoria Island",
      description:
        "Compact and elegantly designed studio apartment on Victoria Island. Ideal for corporate professionals. Includes a kitchenette, en-suite bathroom, and 24/7 security. Walking distance to top restaurants and banks.",
      price: 750000,
      location: "Victoria Island, Lagos",
      type: "Studio",
      rooms: 1,
      amenities: JSON.stringify(["WiFi", "Air Conditioning", "Generator", "Security", "Gym"]),
      verified: true,
      is_available: true,
      views: 303,
      images: [IMG.studio, IMG.room4],
      videos: [],
      slug: slug("Studio Apartment Victoria Island"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_2,
      title: "4-Bedroom Duplex, Magodo Phase 2",
      description:
        "Spacious 4-bedroom duplex in the serene Magodo Phase 2 estate. Features a large compound, boys' quarters, fitted kitchen, and a rooftop terrace. Secure estate with gate house and CCTV.",
      price: 1800000,
      location: "Magodo Phase 2, Lagos",
      type: "Duplex",
      rooms: 4,
      amenities: JSON.stringify(["Generator", "Security", "Parking", "Boys Quarters", "CCTV", "Water"]),
      verified: true,
      is_available: true,
      views: 98,
      images: [IMG.duplex, IMG.house2, IMG.ext1],
      videos: [],
      slug: slug("4-Bedroom Duplex Magodo Phase 2"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_3,
      title: "3-Bedroom Bungalow, Ikorodu",
      description:
        "Affordable 3-bedroom bungalow in a quiet, family-friendly area of Ikorodu. Features a spacious compound, tiled floors, and reliable borehole water supply. Excellent for families.",
      price: 350000,
      location: "Ikorodu, Lagos",
      type: "Bungalow",
      rooms: 3,
      amenities: JSON.stringify(["Borehole Water", "Security", "Parking", "Tiled Floors"]),
      verified: false,
      is_available: true,
      views: 43,
      images: [IMG.house1, IMG.ext2],
      videos: [],
      slug: slug("3-Bedroom Bungalow Ikorodu"),
      created_at: now,
      updated_at: now,
    },

    // ── Abuja ─────────────────────────────────────────────────────────────────
    {
      id: uuidv4(),
      owner_id: OWNER_1,
      title: "Executive 3-Bedroom Apartment, Maitama",
      description:
        "Prestigious fully-furnished executive apartment in Maitama, Abuja. Situated in a serene cul-de-sac with manicured gardens, a rooftop lounge, and top-tier security. Ideal for diplomats and senior executives.",
      price: 2200000,
      location: "Maitama, Abuja",
      type: "Apartment",
      rooms: 3,
      amenities: JSON.stringify(["WiFi", "Air Conditioning", "Generator", "Security", "Swimming Pool", "Gym", "Parking"]),
      verified: true,
      is_available: true,
      views: 412,
      images: [IMG.apt3, IMG.room1, IMG.ext1],
      videos: [],
      slug: slug("Executive 3-Bedroom Apartment Maitama"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_2,
      title: "2-Bedroom Flat, Wuse 2",
      description:
        "Well-maintained 2-bedroom flat in the bustling Wuse 2 district. Close to banks, supermarkets, and restaurants. Features a modern kitchen, tiled bathrooms, and estate-managed security.",
      price: 700000,
      location: "Wuse 2, Abuja",
      type: "Apartment",
      rooms: 2,
      amenities: JSON.stringify(["WiFi", "Generator", "Security", "Parking", "Air Conditioning"]),
      verified: true,
      is_available: true,
      views: 189,
      images: [IMG.apt1, IMG.room3],
      videos: [],
      slug: slug("2-Bedroom Flat Wuse 2"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_3,
      title: "Mini Flat, Garki Area 11",
      description:
        "Budget-friendly mini flat in Garki, suitable for single occupancy or couples. Close to government offices and the National Hospital. Includes water and reliable electricity.",
      price: 280000,
      location: "Garki Area 11, Abuja",
      type: "Self-contain",
      rooms: 1,
      amenities: JSON.stringify(["Water", "Security", "Tiled Floors"]),
      verified: false,
      is_available: true,
      views: 62,
      images: [IMG.studio, IMG.room2],
      videos: [],
      slug: slug("Mini Flat Garki Area 11"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_1,
      title: "5-Bedroom Detached House, Asokoro",
      description:
        "Grand 5-bedroom detached house in the exclusive Asokoro district. Comes with a swimming pool, boys' quarters, cinema room, and a staff room. The compound features lush tropical gardens and automated gate.",
      price: 4500000,
      location: "Asokoro, Abuja",
      type: "House",
      rooms: 5,
      amenities: JSON.stringify(["WiFi", "Swimming Pool", "Generator", "Security", "CCTV", "Gym", "Parking", "Boys Quarters"]),
      verified: true,
      is_available: true,
      views: 537,
      images: [IMG.house3, IMG.ext1, IMG.room1],
      videos: [],
      slug: slug("5-Bedroom Detached House Asokoro"),
      created_at: now,
      updated_at: now,
    },

    // ── Port Harcourt ─────────────────────────────────────────────────────────
    {
      id: uuidv4(),
      owner_id: OWNER_2,
      title: "3-Bedroom Flat, GRA Phase 2, Port Harcourt",
      description:
        "Spacious 3-bedroom flat in the highly sought-after GRA Phase 2, Port Harcourt. Fully serviced with 24-hour electricity from dedicated transformer. Great for oil & gas professionals.",
      price: 1100000,
      location: "GRA Phase 2, Port Harcourt",
      type: "Apartment",
      rooms: 3,
      amenities: JSON.stringify(["24hr Electricity", "Generator", "Security", "Parking", "Air Conditioning"]),
      verified: true,
      is_available: true,
      views: 221,
      images: [IMG.apt2, IMG.room4, IMG.ext2],
      videos: [],
      slug: slug("3-Bedroom Flat GRA Phase 2 Port Harcourt"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_3,
      title: "2-Bedroom Apartment, Rumuola",
      description:
        "Clean and modern 2-bedroom apartment in Rumuola, close to Trans-Amadi industrial area. Tiled throughout, with a fitted kitchen and borehole water. Suitable for families and professionals.",
      price: 450000,
      location: "Rumuola, Port Harcourt",
      type: "Apartment",
      rooms: 2,
      amenities: JSON.stringify(["Borehole Water", "Security", "Tiled Floors", "Parking"]),
      verified: false,
      is_available: true,
      views: 74,
      images: [IMG.apt3, IMG.room2],
      videos: [],
      slug: slug("2-Bedroom Apartment Rumuola"),
      created_at: now,
      updated_at: now,
    },

    // ── Ibadan ────────────────────────────────────────────────────────────────
    {
      id: uuidv4(),
      owner_id: OWNER_1,
      title: "3-Bedroom Bungalow, Bodija Estate",
      description:
        "Well-finished 3-bedroom bungalow in the prestigious Bodija Estate, Ibadan. Featuring large rooms, a spacious kitchen, private compound with fruit trees, and a secured gate. Very peaceful neighbourhood.",
      price: 420000,
      location: "Bodija Estate, Ibadan",
      type: "Bungalow",
      rooms: 3,
      amenities: JSON.stringify(["Security", "Parking", "Water", "Tiled Floors"]),
      verified: true,
      is_available: true,
      views: 96,
      images: [IMG.house1, IMG.room3, IMG.ext2],
      videos: [],
      slug: slug("3-Bedroom Bungalow Bodija Estate Ibadan"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_2,
      title: "1-Bedroom Studio, UI Road, Ibadan",
      description:
        "Compact studio apartment steps from University of Ibadan. Ideal for postgraduate students and young professionals. Includes prepaid electricity metre, tiled floors, and burglar-proof windows.",
      price: 120000,
      location: "UI Road, Ibadan",
      type: "Studio",
      rooms: 1,
      amenities: JSON.stringify(["Prepaid Metre", "Tiled Floors", "Security"]),
      verified: false,
      is_available: true,
      views: 38,
      images: [IMG.studio, IMG.room4],
      videos: [],
      slug: slug("1-Bedroom Studio UI Road Ibadan"),
      created_at: now,
      updated_at: now,
    },

    // ── Enugu ─────────────────────────────────────────────────────────────────
    {
      id: uuidv4(),
      owner_id: OWNER_3,
      title: "4-Bedroom Duplex, Independence Layout, Enugu",
      description:
        "Beautiful 4-bedroom duplex in the serene Independence Layout. Features an upstairs master suite with walk-in closet, a large sitting room, and tiled veranda. Mature estate with 24-hour security patrols.",
      price: 900000,
      location: "Independence Layout, Enugu",
      type: "Duplex",
      rooms: 4,
      amenities: JSON.stringify(["Generator", "Security", "Parking", "CCTV", "Water"]),
      verified: true,
      is_available: true,
      views: 112,
      images: [IMG.duplex, IMG.house2, IMG.room1],
      videos: [],
      slug: slug("4-Bedroom Duplex Independence Layout Enugu"),
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      owner_id: OWNER_1,
      title: "2-Bedroom Flat, New Haven, Enugu",
      description:
        "Affordable and tidy 2-bedroom flat in New Haven. Suitable for a small family or working couple. Water board supply plus borehole backup. Close to New Haven shopping mall.",
      price: 300000,
      location: "New Haven, Enugu",
      type: "Apartment",
      rooms: 2,
      amenities: JSON.stringify(["Borehole Water", "Tiled Floors", "Security"]),
      verified: false,
      is_available: true,
      views: 55,
      images: [IMG.apt1, IMG.room2],
      videos: [],
      slug: slug("2-Bedroom Flat New Haven Enugu"),
      created_at: now,
      updated_at: now,
    },

    // ── Kano ──────────────────────────────────────────────────────────────────
    {
      id: uuidv4(),
      owner_id: OWNER_2,
      title: "3-Bedroom House, Nassarawa GRA, Kano",
      description:
        "Solid 3-bedroom house in Nassarawa GRA, Kano. Large compound with a garden, a separate borehole, solar panels for electricity, and a recently upgraded kitchen. Quiet and family-oriented neighbourhood.",
      price: 500000,
      location: "Nassarawa GRA, Kano",
      type: "House",
      rooms: 3,
      amenities: JSON.stringify(["Solar Panels", "Borehole Water", "Security", "Parking", "Garden"]),
      verified: true,
      is_available: true,
      views: 88,
      images: [IMG.house3, IMG.ext1, IMG.room3],
      videos: [],
      slug: slug("3-Bedroom House Nassarawa GRA Kano"),
      created_at: now,
      updated_at: now,
    },

    // ── Calabar ───────────────────────────────────────────────────────────────
    {
      id: uuidv4(),
      owner_id: OWNER_3,
      title: "2-Bedroom Apartment, State Housing, Calabar",
      description:
        "Neat and serene 2-bedroom apartment in Calabar's State Housing estate. Well-ventilated rooms, polished floors, and a quiet communal courtyard. Great value in one of Nigeria's cleanest cities.",
      price: 260000,
      location: "State Housing, Calabar",
      type: "Apartment",
      rooms: 2,
      amenities: JSON.stringify(["Water", "Security", "Tiled Floors"]),
      verified: false,
      is_available: true,
      views: 29,
      images: [IMG.apt2, IMG.room4],
      videos: [],
      slug: slug("2-Bedroom Apartment State Housing Calabar"),
      created_at: now,
      updated_at: now,
    },

    // ── Warri ─────────────────────────────────────────────────────────────────
    {
      id: uuidv4(),
      owner_id: OWNER_1,
      title: "Office Space, Okumagba Avenue, Warri",
      description:
        "Prime commercial office space on Okumagba Avenue, Warri's main business corridor. Open-plan layout with 4 private offices, a boardroom, reception, and 2 restrooms. Generator and dedicated parking available.",
      price: 800000,
      location: "Okumagba Avenue, Warri",
      type: "Office",
      rooms: null,
      amenities: JSON.stringify(["Generator", "Air Conditioning", "Parking", "Security", "WiFi"]),
      verified: true,
      is_available: true,
      views: 143,
      images: [IMG.office, IMG.ext2],
      videos: [],
      slug: slug("Office Space Okumagba Avenue Warri"),
      created_at: now,
      updated_at: now,
    },

    // ── Benin City ─────────────────────────────────────────────────────────────
    {
      id: uuidv4(),
      owner_id: OWNER_2,
      title: "3-Bedroom Bungalow, GRA, Benin City",
      description:
        "Spacious 3-bedroom bungalow in the Benin GRA. Comes with a large compound, fruit trees, and separate BQ. Recently painted and re-tiled. Close to University of Benin Teaching Hospital.",
      price: 480000,
      location: "GRA, Benin City",
      type: "Bungalow",
      rooms: 3,
      amenities: JSON.stringify(["Borehole Water", "Security", "Parking", "Boys Quarters"]),
      verified: true,
      is_available: true,
      views: 67,
      images: [IMG.house1, IMG.room1, IMG.ext1],
      videos: [],
      slug: slug("3-Bedroom Bungalow GRA Benin City"),
      created_at: now,
      updated_at: now,
    },
  ];

  await knex(DB_TABLES.PROPERTIES).insert(properties);

  console.log(`✓ Seeded ${properties.length} properties across 8 Nigerian cities`);
}
